import { useCallback, useEffect, useMemo, useState, type ComponentProps } from 'react';
import { FlatList, Image, Pressable, RefreshControl, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppHeader, AppText, Card, Chip, EmptyState as BaseEmptyState, LoadingView, Screen as BaseScreen, StatusPill, useAppTheme } from '@/design-system';
import { listDates, mediaContentUrl, type DateProposal } from '@/features/api/mobile-api';

const terminal = new Set(['DECLINED', 'CANCELLED', 'COMPLETED']);
const Screen = (props: ComponentProps<typeof BaseScreen>) => <BaseScreen scroll={false} {...props} />;
const EmptyState = (props: ComponentProps<typeof BaseEmptyState>) => <BaseEmptyState {...props} icon={typeof props.icon === 'string' ? <Ionicons name="calendar-outline" size={38} /> : props.icon} />;
const status: Record<string, { label: string; tone: 'primary' | 'success' | 'warning' | 'neutral' | 'danger' }> = { PENDING_CONFIRMATION: { label: 'Ждёт ответа', tone: 'warning' }, ACCEPTED: { label: 'Подтверждено', tone: 'success' }, DECLINED: { label: 'Отклонено', tone: 'neutral' }, CANCELLED: { label: 'Отменено', tone: 'danger' }, COMPLETED: { label: 'Состоялось', tone: 'primary' } };
const formatDate = (value: string) => new Intl.DateTimeFormat('ru-RU', { weekday: 'short', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export default function DatesScreen() {
  const theme = useAppTheme(); const [items, setItems] = useState<DateProposal[]>([]); const [tab, setTab] = useState<'upcoming' | 'history'>('upcoming'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(false);
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(false); try { setItems(await listDates()); } catch { setError(true); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => items.filter(item => tab === 'history' ? terminal.has(item.status) || new Date(item.scheduledAt) < new Date() : !terminal.has(item.status) && new Date(item.scheduledAt) >= new Date()).sort((a, b) => tab === 'history' ? +new Date(b.scheduledAt) - +new Date(a.scheduledAt) : +new Date(a.scheduledAt) - +new Date(b.scheduledAt)), [items, tab]);
  return <Screen edges={['top']} style={styles.screen}><AppHeader title="Наши свидания" subtitle="Планы, которые становятся воспоминаниями" actionIcon="add" onAction={() => router.push('/new-date')} /><View style={styles.tabs}><Chip label="Предстоящие" selected={tab === 'upcoming'} onPress={() => setTab('upcoming')} /><Chip label="История" selected={tab === 'history'} onPress={() => setTab('history')} /></View>{loading ? <LoadingView label="Загружаем ваши планы…" /> : <FlatList data={visible} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={theme.colors.primary} />} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} ListEmptyComponent={<EmptyState icon="calendar-outline" title={error ? 'Свидания не загрузились' : tab === 'upcoming' ? 'Самое время что-нибудь придумать' : 'Здесь появятся ваши воспоминания'} description={error ? 'Проверьте соединение и попробуйте снова.' : tab === 'upcoming' ? 'Выберите место или событие и пригласите любимого человека.' : 'Прошедшие свидания будут собраны здесь.'} actionLabel={error ? 'Повторить' : tab === 'upcoming' ? 'Создать свидание' : undefined} onAction={error ? () => void load() : tab === 'upcoming' ? () => router.push('/new-date') : undefined} />} renderItem={({ item }) => { const state = status[item.status] ?? { label: item.status, tone: 'neutral' as const }; return <Pressable accessibilityRole="button" accessibilityLabel={`${item.eventTitle ?? item.placeName}, ${formatDate(item.scheduledAt)}, ${state.label}`} onPress={() => router.push({ pathname: '/date/[id]', params: { id: item.id } })}><Card style={styles.card}>{item.placeCoverMediaId ? <Image accessibilityLabel="Фото места" source={{ uri: mediaContentUrl(item.placeCoverMediaId, 'THUMBNAIL') }} style={styles.image} /> : <View style={[styles.icon, { backgroundColor: theme.colors.primarySoft }]}><Ionicons name={item.eventId ? 'ticket-outline' : 'heart-outline'} size={25} color={theme.colors.primary} /></View>}<View style={styles.body}><AppText variant="title3" numberOfLines={1}>{item.eventTitle ?? item.placeName}</AppText><AppText variant="bodySmall" color="muted">{formatDate(item.scheduledAt)}</AppText><StatusPill label={state.label} tone={state.tone} /></View><Ionicons name="chevron-forward" size={20} color={theme.colors.muted} /></Card></Pressable>; }} />}</Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, tabs: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 14, gap: 8 }, list: { paddingHorizontal: 20, paddingBottom: 120, gap: 12, flexGrow: 1 }, card: { flexDirection: 'row', alignItems: 'center', gap: 13 }, icon: { width: 54, height: 64, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, image: { width: 54, height: 64, borderRadius: 18 }, body: { flex: 1, alignItems: 'flex-start', gap: 6 } });
