import { useCallback, useEffect, useMemo, useState, type ComponentProps } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import { AppHeader, AppText, Card, Chip, EmptyState, LoadingView, Screen as BaseScreen, useAppTheme } from '@/design-system';
import { getEvents, type Event } from '@/features/api/mobile-api';

const filters = ['Все', 'Бесплатно', 'Концерты', 'Театр', 'Выставки'];
const Screen = (props: ComponentProps<typeof BaseScreen>) => <BaseScreen scroll={false} {...props} />;
const dateLabel = (value?: string) => value ? new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : 'Дата уточняется';
export default function EventsScreen() {
  const theme = useAppTheme(); const [items, setItems] = useState<Event[]>([]); const [filter, setFilter] = useState('Все'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(false);
  const apiFilter = useMemo(() => ({ free: filter === 'Бесплатно' ? true : undefined, category: ({ Концерты: 'concert', Театр: 'theater', Выставки: 'exhibition' } as Record<string, string>)[filter] }), [filter]);
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(false); try { setItems((await getEvents(apiFilter)).items); } catch { setError(true); } finally { setLoading(false); setRefreshing(false); } }, [apiFilter]);
  useEffect(() => { void load(); }, [load]);
  return <Screen edges={['top']} style={styles.screen}><AppHeader title="Афиша для двоих" subtitle="Идеи на ближайшие вечера" /><FlatList horizontal data={filters} keyExtractor={item => item} renderItem={({ item }) => <Chip label={item} selected={filter === item} onPress={() => setFilter(item)} />} contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false} style={styles.chipList} />{loading ? <LoadingView label="Собираем интересные события…" /> : <FlatList data={items} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={theme.colors.primary} />} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} ListEmptyComponent={<EmptyState title={error ? 'Афиша не загрузилась' : 'Пока событий нет'} description={error ? 'Проверьте соединение и попробуйте снова.' : 'Загляните чуть позже — мы обновляем подборку.'} actionLabel={error ? 'Повторить' : undefined} onAction={error ? () => void load() : undefined} />} renderItem={({ item }) => { const hero = item.images[0]?.thumbnailUrl ?? item.images[0]?.remoteUrl; return <Pressable accessibilityRole="button" accessibilityLabel={`${item.title}, ${dateLabel(item.occurrences[0]?.startsAt)}`} onPress={() => router.push({ pathname: '/event/[id]' as never, params: { id: item.id } } as never)}><Card padding={0} style={styles.card}><View style={[styles.photo, { backgroundColor: theme.colors.primarySoft }]}>{hero ? <Image source={hero} style={StyleSheet.absoluteFill} contentFit="cover" transition={250} /> : <Ionicons name="ticket-outline" size={48} color={theme.colors.primary} />}<View style={styles.dateBadge}><AppText variant="label" style={styles.white}>{dateLabel(item.occurrences[0]?.startsAt)}</AppText></View>{item.free ? <View style={styles.freeBadge}><AppText variant="caption" style={styles.white}>Бесплатно</AppText></View> : null}</View><View style={styles.body}><AppText variant="title3" numberOfLines={2}>{item.title}</AppText><View style={styles.row}><Ionicons name="location-outline" size={16} color={theme.colors.muted} /><AppText variant="bodySmall" color="muted" numberOfLines={1} style={styles.flex}>{item.venueName ?? item.venueAddress ?? 'Место уточняется'}</AppText></View>{item.priceText ? <AppText variant="label" color="primary">{item.priceText}</AppText> : null}</View></Card></Pressable>; }} />}</Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, chipList: { flexGrow: 0 }, chips: { paddingHorizontal: 20, paddingVertical: 14, gap: 8 }, list: { paddingHorizontal: 20, paddingBottom: 120, gap: 16, flexGrow: 1 }, card: { overflow: 'hidden' }, photo: { height: 205, alignItems: 'center', justifyContent: 'center' }, dateBadge: { position: 'absolute', left: 12, bottom: 12, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 12, backgroundColor: 'rgba(32,21,28,0.82)' }, freeBadge: { position: 'absolute', right: 12, top: 12, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 99, backgroundColor: '#2E7D5A' }, white: { color: '#fff' }, body: { padding: 16, gap: 9 }, row: { flexDirection: 'row', alignItems: 'center', gap: 6 }, flex: { flex: 1 } });
