import { useCallback, useEffect, useRef, useState, type ComponentProps } from 'react';
import { Alert, Image, ScrollView, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { AppHeader, AppText, Button, Card, EmptyState, LoadingView, Screen as BaseScreen, StatusPill, useAppTheme } from '@/design-system';
import { createIdempotencyKey, decideDate, getDate, mediaContentUrl, type DateProposal } from '@/features/api/mobile-api';

const Screen = (props: ComponentProps<typeof BaseScreen>) => <BaseScreen scroll={false} {...props} />;

const status: Record<string, { label: string; tone: 'primary' | 'success' | 'warning' | 'neutral' | 'danger'; message: string }> = { PENDING_CONFIRMATION: { label: 'Ждёт ответа', tone: 'warning', message: 'Приглашение отправлено и ждёт решения.' }, ACCEPTED: { label: 'Подтверждено', tone: 'success', message: 'Вы оба согласились — прекрасного вечера!' }, DECLINED: { label: 'Отклонено', tone: 'neutral', message: 'Это приглашение было отклонено.' }, CANCELLED: { label: 'Отменено', tone: 'danger', message: 'Планы изменились, и свидание отменено.' }, COMPLETED: { label: 'Состоялось', tone: 'primary', message: 'Ещё одно ваше общее воспоминание.' } };
const formatDate = (value: string) => new Intl.DateTimeFormat('ru-RU', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export default function DateScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const theme = useAppTheme(); const [date, setDate] = useState<DateProposal | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [acting, setActing] = useState(false); const actionKeys = useRef<Partial<Record<'accept' | 'decline' | 'cancel', string>>>({});
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(false); try { setDate(await getDate(id)); } catch { setError(true); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const action = async (value: 'accept' | 'decline' | 'cancel') => { if (!date || acting) return; if (!actionKeys.current[value]) actionKeys.current[value] = createIdempotencyKey(); setActing(true); try { setDate(await decideDate(date.id, value, actionKeys.current[value])); actionKeys.current[value] = undefined; } catch { Alert.alert('Не получилось обновить свидание', 'Попробуйте ещё раз — повторный запрос будет безопасным.'); } finally { setActing(false); } };
  const confirm = (value: 'decline' | 'cancel') => Alert.alert(value === 'decline' ? 'Отклонить приглашение?' : 'Отменить свидание?', 'Партнёр получит уведомление об изменении планов.', [{ text: 'Не сейчас', style: 'cancel' }, { text: value === 'decline' ? 'Отклонить' : 'Отменить', style: 'destructive', onPress: () => void action(value) }]);
  if (loading) return <Screen><LoadingView label="Открываем свидание…" /></Screen>; if (!date || error) return <Screen><AppHeader title="Свидание" showBack /><EmptyState title="Не удалось открыть свидание" description="Проверьте соединение и попробуйте снова." actionLabel="Повторить" onAction={() => void load()} /></Screen>;
  const state = status[date.status] ?? { label: date.status, tone: 'neutral' as const, message: 'Статус свидания обновлён.' };
  return <Screen edges={['top']} style={styles.screen}><AppHeader title="Наше свидание" showBack /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={[styles.postcard, { backgroundColor: theme.colors.primarySoft }]}>{date.placeCoverMediaId ? <Image accessibilityLabel="Фото места" source={{ uri: mediaContentUrl(date.placeCoverMediaId, 'DETAIL') }} style={styles.photo} /> : <Ionicons name={date.eventId ? 'ticket' : 'heart'} size={40} color={theme.colors.primary} />}<AppText variant="eyebrow" color="primary">ПРИГЛАШЕНИЕ ДЛЯ ДВОИХ</AppText><AppText variant="displaySmall" style={styles.center}>{date.eventTitle ?? date.placeName}</AppText><AppText color="muted" style={styles.center}>{formatDate(date.scheduledAt)}</AppText></View><View style={styles.statusRow}><StatusPill label={state.label} tone={state.tone} /><AppText variant="bodySmall" color="muted" style={styles.statusMessage}>{state.message}</AppText></View><Card><View style={styles.detailRow}><Ionicons name="location-outline" size={22} color={theme.colors.primary} /><View style={styles.flex}><AppText variant="label">Место</AppText><AppText color="muted">{date.placeName || date.eventTitle}</AppText>{date.placeAddress ? <AppText variant="bodySmall" color="muted">{date.placeAddress}</AppText> : null}</View></View><View style={styles.divider} /><View style={styles.detailRow}><Ionicons name="calendar-outline" size={22} color={theme.colors.primary} /><View style={styles.flex}><AppText variant="label">Когда</AppText><AppText color="muted">{formatDate(date.scheduledAt)}</AppText></View></View></Card>{date.description ? <Card><AppText variant="eyebrow" color="primary">ЛИЧНАЯ ЗАМЕТКА</AppText><AppText style={styles.note}>{date.description}</AppText></Card> : null}</ScrollView><View style={[styles.footer, { backgroundColor: theme.colors.background, borderTopColor: theme.colors.border }]}>{date.status === 'PENDING_CONFIRMATION' ? <View style={styles.actions}><Button label="Принять" loading={acting} style={styles.flex} onPress={() => void action('accept')} /><Button label="Отклонить" variant="secondary" disabled={acting} style={styles.flex} onPress={() => confirm('decline')} /></View> : null}{!['CANCELLED', 'DECLINED', 'COMPLETED'].includes(date.status) ? <Button label="Отменить планы" variant="ghost" disabled={acting} onPress={() => confirm('cancel')} /> : null}</View></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, content: { padding: 20, paddingBottom: 150, gap: 16 }, postcard: { minHeight: 260, borderRadius: 32, borderBottomLeftRadius: 8, padding: 26, alignItems: 'center', justifyContent: 'center', gap: 14 }, photo: { width: '100%', height: 150, borderRadius: 20 }, center: { textAlign: 'center' }, statusRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, statusMessage: { flex: 1 }, detailRow: { flexDirection: 'row', gap: 12 }, flex: { flex: 1 }, divider: { height: StyleSheet.hairlineWidth, backgroundColor: 'rgba(128,90,105,.25)', marginVertical: 15 }, note: { marginTop: 8, fontStyle: 'italic', lineHeight: 24 }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 22, borderTopWidth: StyleSheet.hairlineWidth, gap: 8 }, actions: { flexDirection: 'row', gap: 10 } });
