spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/dating_notification}
    username: ${NOTIFICATION_DB_USERNAME:dating_notification}
    password: ${NOTIFICATION_DB_PASSWORD:dating_notification}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:dating-redis}
      database: ${NOTIFICATION_REDIS_DATABASE:1}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-v1
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${NOTIFICATION_SERVICE_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
