import { useCallback, useEffect, useMemo, useState, type ComponentProps } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { router, useLocalSearchParams } from 'expo-router';
import { AppHeader, AppText, Button, Card, EmptyState, LoadingView, Screen as BaseScreen, StatusPill, useAppTheme } from '@/design-system';
import { getEvent, type Event } from '@/features/api/mobile-api';

const Screen = (props: ComponentProps<typeof BaseScreen>) => <BaseScreen scroll={false} {...props} />;

const formatDate = (value: string) => new Intl.DateTimeFormat('ru-RU', { weekday: 'short', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export default function EventDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const theme = useAppTheme(); const [event, setEvent] = useState<Event | null>(null); const [selected, setSelected] = useState<string>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(false); try { const result = await getEvent(id); setEvent(result); setSelected(result.occurrences.find(item => new Date(item.startsAt) > new Date())?.id ?? result.occurrences[0]?.id); } catch { setError(true); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const occurrence = useMemo(() => event?.occurrences.find(item => item.id === selected), [event, selected]);
  if (loading) return <Screen><LoadingView label="Открываем событие…" /></Screen>;
  if (!event || error) return <Screen><AppHeader title="Событие" showBack /><EmptyState title="Событие не загрузилось" description="Попробуйте ещё раз." actionLabel="Повторить" onAction={() => void load()} /></Screen>;
  const hero = event.images[0]?.remoteUrl ?? event.images[0]?.thumbnailUrl;
  return <Screen edges={['top']} style={styles.screen}><AppHeader title="Афиша" showBack /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={[styles.hero, { backgroundColor: theme.colors.primarySoft }]}>{hero ? <Image source={hero} style={StyleSheet.absoluteFill} contentFit="cover" transition={250} /> : <Ionicons name="ticket-outline" size={58} color={theme.colors.primary} />}</View><View style={styles.heading}>{event.free ? <StatusPill label="Бесплатно" tone="success" /> : null}<AppText variant="displaySmall">{event.title}</AppText><View style={styles.row}><Ionicons name="location-outline" size={18} color={theme.colors.muted} /><AppText color="muted" style={styles.flex}>{event.venueName ?? event.venueAddress ?? 'Место уточняется'}</AppText></View>{event.priceText ? <AppText variant="label" color="primary">{event.priceText}</AppText> : null}</View>{event.description ? <Card><AppText variant="title3">О событии</AppText><AppText color="muted" style={styles.description}>{event.description}</AppText></Card> : null}<View style={styles.occurrences}><AppText variant="title3">Выберите сеанс</AppText>{event.occurrences.length ? event.occurrences.map(item => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{ checked: selected === item.id }} onPress={() => setSelected(item.id)} style={[styles.occurrence, { borderColor: selected === item.id ? theme.colors.primary : theme.colors.border, backgroundColor: selected === item.id ? theme.colors.primarySoft : theme.colors.surface }]}><Ionicons name={selected === item.id ? 'radio-button-on' : 'radio-button-off'} size={22} color={selected === item.id ? theme.colors.primary : theme.colors.muted} /><AppText variant="label" style={styles.flex}>{formatDate(item.startsAt)}</AppText></Pressable>) : <AppText color="muted">Расписание ещё не опубликовано.</AppText>}</View></ScrollView><View style={[styles.footer, { backgroundColor: theme.colors.background, borderTopColor: theme.colors.border }]}><Button label="Предложить свидание" disabled={!occurrence} onPress={() => occurrence ? router.push({ pathname: '/new-date', params: { occurrenceId: occurrence.id, eventId: event.id, name: event.title, scheduledAt: occurrence.startsAt } }) : Alert.alert('Нет сеансов', 'Выберите доступный сеанс.')} /></View></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, content: { paddingBottom: 120, gap: 20 }, hero: { height: 310, alignItems: 'center', justifyContent: 'center' }, heading: { paddingHorizontal: 20, gap: 9 }, row: { flexDirection: 'row', alignItems: 'center', gap: 7 }, flex: { flex: 1 }, description: { marginTop: 8, lineHeight: 23 }, occurrences: { paddingHorizontal: 20, gap: 10 }, occurrence: { minHeight: 54, borderRadius: 18, borderWidth: 1, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 24, borderTopWidth: StyleSheet.hairlineWidth } });
